// Code generated by "enumer -type=Access -trimprefix=Access -json -yaml -output=access_string.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AccessName = "UnknownNotImplementedNotAccessibleNotifyReadOnlyReadWriteInstallInstallNotifyReportOnlyEventOnly"

var _AccessIndex = [...]uint8{0, 7, 21, 34, 40, 48, 57, 64, 77, 87, 96}

const _AccessLowerName = "unknownnotimplementednotaccessiblenotifyreadonlyreadwriteinstallinstallnotifyreportonlyeventonly"

func (i Access) String() string {
	if i < 0 || i >= Access(len(_AccessIndex)-1) {
		return fmt.Sprintf("Access(%d)", i)
	}
	return _AccessName[_AccessIndex[i]:_AccessIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AccessNoOp() {
	var x [1]struct{}
	_ = x[AccessUnknown-(0)]
	_ = x[AccessNotImplemented-(1)]
	_ = x[AccessNotAccessible-(2)]
	_ = x[AccessNotify-(3)]
	_ = x[AccessReadOnly-(4)]
	_ = x[AccessReadWrite-(5)]
	_ = x[AccessInstall-(6)]
	_ = x[AccessInstallNotify-(7)]
	_ = x[AccessReportOnly-(8)]
	_ = x[AccessEventOnly-(9)]
}

var _AccessValues = []Access{AccessUnknown, AccessNotImplemented, AccessNotAccessible, AccessNotify, AccessReadOnly, AccessReadWrite, AccessInstall, AccessInstallNotify, AccessReportOnly, AccessEventOnly}

var _AccessNameToValueMap = map[string]Access{
	_AccessName[0:7]:        AccessUnknown,
	_AccessLowerName[0:7]:   AccessUnknown,
	_AccessName[7:21]:       AccessNotImplemented,
	_AccessLowerName[7:21]:  AccessNotImplemented,
	_AccessName[21:34]:      AccessNotAccessible,
	_AccessLowerName[21:34]: AccessNotAccessible,
	_AccessName[34:40]:      AccessNotify,
	_AccessLowerName[34:40]: AccessNotify,
	_AccessName[40:48]:      AccessReadOnly,
	_AccessLowerName[40:48]: AccessReadOnly,
	_AccessName[48:57]:      AccessReadWrite,
	_AccessLowerName[48:57]: AccessReadWrite,
	_AccessName[57:64]:      AccessInstall,
	_AccessLowerName[57:64]: AccessInstall,
	_AccessName[64:77]:      AccessInstallNotify,
	_AccessLowerName[64:77]: AccessInstallNotify,
	_AccessName[77:87]:      AccessReportOnly,
	_AccessLowerName[77:87]: AccessReportOnly,
	_AccessName[87:96]:      AccessEventOnly,
	_AccessLowerName[87:96]: AccessEventOnly,
}

var _AccessNames = []string{
	_AccessName[0:7],
	_AccessName[7:21],
	_AccessName[21:34],
	_AccessName[34:40],
	_AccessName[40:48],
	_AccessName[48:57],
	_AccessName[57:64],
	_AccessName[64:77],
	_AccessName[77:87],
	_AccessName[87:96],
}

// AccessString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AccessString(s string) (Access, error) {
	if val, ok := _AccessNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AccessNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Access values", s)
}

// AccessValues returns all values of the enum
func AccessValues() []Access {
	return _AccessValues
}

// AccessStrings returns a slice of all String values of the enum
func AccessStrings() []string {
	strs := make([]string, len(_AccessNames))
	copy(strs, _AccessNames)
	return strs
}

// IsAAccess returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Access) IsAAccess() bool {
	for _, v := range _AccessValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Access
func (i Access) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Access
func (i *Access) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Access should be a string, got %s", data)
	}

	var err error
	*i, err = AccessString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for Access
func (i Access) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Access
func (i *Access) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = AccessString(s)
	return err
}
