// Code generated by "enumer -type=BaseType -trimprefix=BaseType -json -yaml -output=basetype_string.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BaseTypeName = "UnknownInteger32OctetStringObjectIdentifierUnsigned32Integer64Unsigned64Float32Float64Float128EnumBitsPointer"

var _BaseTypeIndex = [...]uint8{0, 7, 16, 27, 43, 53, 62, 72, 79, 86, 94, 98, 102, 109}

const _BaseTypeLowerName = "unknowninteger32octetstringobjectidentifierunsigned32integer64unsigned64float32float64float128enumbitspointer"

func (i BaseType) String() string {
	if i < 0 || i >= BaseType(len(_BaseTypeIndex)-1) {
		return fmt.Sprintf("BaseType(%d)", i)
	}
	return _BaseTypeName[_BaseTypeIndex[i]:_BaseTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BaseTypeNoOp() {
	var x [1]struct{}
	_ = x[BaseTypeUnknown-(0)]
	_ = x[BaseTypeInteger32-(1)]
	_ = x[BaseTypeOctetString-(2)]
	_ = x[BaseTypeObjectIdentifier-(3)]
	_ = x[BaseTypeUnsigned32-(4)]
	_ = x[BaseTypeInteger64-(5)]
	_ = x[BaseTypeUnsigned64-(6)]
	_ = x[BaseTypeFloat32-(7)]
	_ = x[BaseTypeFloat64-(8)]
	_ = x[BaseTypeFloat128-(9)]
	_ = x[BaseTypeEnum-(10)]
	_ = x[BaseTypeBits-(11)]
	_ = x[BaseTypePointer-(12)]
}

var _BaseTypeValues = []BaseType{BaseTypeUnknown, BaseTypeInteger32, BaseTypeOctetString, BaseTypeObjectIdentifier, BaseTypeUnsigned32, BaseTypeInteger64, BaseTypeUnsigned64, BaseTypeFloat32, BaseTypeFloat64, BaseTypeFloat128, BaseTypeEnum, BaseTypeBits, BaseTypePointer}

var _BaseTypeNameToValueMap = map[string]BaseType{
	_BaseTypeName[0:7]:          BaseTypeUnknown,
	_BaseTypeLowerName[0:7]:     BaseTypeUnknown,
	_BaseTypeName[7:16]:         BaseTypeInteger32,
	_BaseTypeLowerName[7:16]:    BaseTypeInteger32,
	_BaseTypeName[16:27]:        BaseTypeOctetString,
	_BaseTypeLowerName[16:27]:   BaseTypeOctetString,
	_BaseTypeName[27:43]:        BaseTypeObjectIdentifier,
	_BaseTypeLowerName[27:43]:   BaseTypeObjectIdentifier,
	_BaseTypeName[43:53]:        BaseTypeUnsigned32,
	_BaseTypeLowerName[43:53]:   BaseTypeUnsigned32,
	_BaseTypeName[53:62]:        BaseTypeInteger64,
	_BaseTypeLowerName[53:62]:   BaseTypeInteger64,
	_BaseTypeName[62:72]:        BaseTypeUnsigned64,
	_BaseTypeLowerName[62:72]:   BaseTypeUnsigned64,
	_BaseTypeName[72:79]:        BaseTypeFloat32,
	_BaseTypeLowerName[72:79]:   BaseTypeFloat32,
	_BaseTypeName[79:86]:        BaseTypeFloat64,
	_BaseTypeLowerName[79:86]:   BaseTypeFloat64,
	_BaseTypeName[86:94]:        BaseTypeFloat128,
	_BaseTypeLowerName[86:94]:   BaseTypeFloat128,
	_BaseTypeName[94:98]:        BaseTypeEnum,
	_BaseTypeLowerName[94:98]:   BaseTypeEnum,
	_BaseTypeName[98:102]:       BaseTypeBits,
	_BaseTypeLowerName[98:102]:  BaseTypeBits,
	_BaseTypeName[102:109]:      BaseTypePointer,
	_BaseTypeLowerName[102:109]: BaseTypePointer,
}

var _BaseTypeNames = []string{
	_BaseTypeName[0:7],
	_BaseTypeName[7:16],
	_BaseTypeName[16:27],
	_BaseTypeName[27:43],
	_BaseTypeName[43:53],
	_BaseTypeName[53:62],
	_BaseTypeName[62:72],
	_BaseTypeName[72:79],
	_BaseTypeName[79:86],
	_BaseTypeName[86:94],
	_BaseTypeName[94:98],
	_BaseTypeName[98:102],
	_BaseTypeName[102:109],
}

// BaseTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BaseTypeString(s string) (BaseType, error) {
	if val, ok := _BaseTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BaseTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BaseType values", s)
}

// BaseTypeValues returns all values of the enum
func BaseTypeValues() []BaseType {
	return _BaseTypeValues
}

// BaseTypeStrings returns a slice of all String values of the enum
func BaseTypeStrings() []string {
	strs := make([]string, len(_BaseTypeNames))
	copy(strs, _BaseTypeNames)
	return strs
}

// IsABaseType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BaseType) IsABaseType() bool {
	for _, v := range _BaseTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BaseType
func (i BaseType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BaseType
func (i *BaseType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BaseType should be a string, got %s", data)
	}

	var err error
	*i, err = BaseTypeString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for BaseType
func (i BaseType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for BaseType
func (i *BaseType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = BaseTypeString(s)
	return err
}
