// Code generated by "enumer -type=Decl -trimprefix=Decl -json -yaml -output=decl_string.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_DeclName_0      = "UnknownImplicitTypeTypeAssignment"
	_DeclLowerName_0 = "unknownimplicittypetypeassignment"
	_DeclName_1      = "ImplSequenceOfValueAssignmentObjectTypeObjectIdentityModuleIdentityNotificationTypeTrapTypeObjectGroupNotificationGroupModuleComplianceAgentCapabilitiesTextualConventionMacroComplGroupComplObjectImplObject"
	_DeclLowerName_1 = "implsequenceofvalueassignmentobjecttypeobjectidentitymoduleidentitynotificationtypetraptypeobjectgroupnotificationgroupmodulecomplianceagentcapabilitiestextualconventionmacrocomplgroupcomplobjectimplobject"
	_DeclName_2      = "ModuleExtensionTypedefNodeScalarTableRowColumnNotificationGroupComplianceIdentityClassAttributeEvent"
	_DeclLowerName_2 = "moduleextensiontypedefnodescalartablerowcolumnnotificationgroupcomplianceidentityclassattributeevent"
)

var (
	_DeclIndex_0 = [...]uint8{0, 7, 19, 33}
	_DeclIndex_1 = [...]uint8{0, 14, 29, 39, 53, 67, 83, 91, 102, 119, 135, 152, 169, 174, 184, 195, 205}
	_DeclIndex_2 = [...]uint8{0, 6, 15, 22, 26, 32, 37, 40, 46, 58, 63, 73, 81, 86, 95, 100}
)

func (i Decl) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _DeclName_0[_DeclIndex_0[i]:_DeclIndex_0[i+1]]
	case 4 <= i && i <= 19:
		i -= 4
		return _DeclName_1[_DeclIndex_1[i]:_DeclIndex_1[i+1]]
	case 33 <= i && i <= 47:
		i -= 33
		return _DeclName_2[_DeclIndex_2[i]:_DeclIndex_2[i+1]]
	default:
		return fmt.Sprintf("Decl(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DeclNoOp() {
	var x [1]struct{}
	_ = x[DeclUnknown-(0)]
	_ = x[DeclImplicitType-(1)]
	_ = x[DeclTypeAssignment-(2)]
	_ = x[DeclImplSequenceOf-(4)]
	_ = x[DeclValueAssignment-(5)]
	_ = x[DeclObjectType-(6)]
	_ = x[DeclObjectIdentity-(7)]
	_ = x[DeclModuleIdentity-(8)]
	_ = x[DeclNotificationType-(9)]
	_ = x[DeclTrapType-(10)]
	_ = x[DeclObjectGroup-(11)]
	_ = x[DeclNotificationGroup-(12)]
	_ = x[DeclModuleCompliance-(13)]
	_ = x[DeclAgentCapabilities-(14)]
	_ = x[DeclTextualConvention-(15)]
	_ = x[DeclMacro-(16)]
	_ = x[DeclComplGroup-(17)]
	_ = x[DeclComplObject-(18)]
	_ = x[DeclImplObject-(19)]
	_ = x[DeclModule-(33)]
	_ = x[DeclExtension-(34)]
	_ = x[DeclTypedef-(35)]
	_ = x[DeclNode-(36)]
	_ = x[DeclScalar-(37)]
	_ = x[DeclTable-(38)]
	_ = x[DeclRow-(39)]
	_ = x[DeclColumn-(40)]
	_ = x[DeclNotification-(41)]
	_ = x[DeclGroup-(42)]
	_ = x[DeclCompliance-(43)]
	_ = x[DeclIdentity-(44)]
	_ = x[DeclClass-(45)]
	_ = x[DeclAttribute-(46)]
	_ = x[DeclEvent-(47)]
}

var _DeclValues = []Decl{DeclUnknown, DeclImplicitType, DeclTypeAssignment, DeclImplSequenceOf, DeclValueAssignment, DeclObjectType, DeclObjectIdentity, DeclModuleIdentity, DeclNotificationType, DeclTrapType, DeclObjectGroup, DeclNotificationGroup, DeclModuleCompliance, DeclAgentCapabilities, DeclTextualConvention, DeclMacro, DeclComplGroup, DeclComplObject, DeclImplObject, DeclModule, DeclExtension, DeclTypedef, DeclNode, DeclScalar, DeclTable, DeclRow, DeclColumn, DeclNotification, DeclGroup, DeclCompliance, DeclIdentity, DeclClass, DeclAttribute, DeclEvent}

var _DeclNameToValueMap = map[string]Decl{
	_DeclName_0[0:7]:          DeclUnknown,
	_DeclLowerName_0[0:7]:     DeclUnknown,
	_DeclName_0[7:19]:         DeclImplicitType,
	_DeclLowerName_0[7:19]:    DeclImplicitType,
	_DeclName_0[19:33]:        DeclTypeAssignment,
	_DeclLowerName_0[19:33]:   DeclTypeAssignment,
	_DeclName_1[0:14]:         DeclImplSequenceOf,
	_DeclLowerName_1[0:14]:    DeclImplSequenceOf,
	_DeclName_1[14:29]:        DeclValueAssignment,
	_DeclLowerName_1[14:29]:   DeclValueAssignment,
	_DeclName_1[29:39]:        DeclObjectType,
	_DeclLowerName_1[29:39]:   DeclObjectType,
	_DeclName_1[39:53]:        DeclObjectIdentity,
	_DeclLowerName_1[39:53]:   DeclObjectIdentity,
	_DeclName_1[53:67]:        DeclModuleIdentity,
	_DeclLowerName_1[53:67]:   DeclModuleIdentity,
	_DeclName_1[67:83]:        DeclNotificationType,
	_DeclLowerName_1[67:83]:   DeclNotificationType,
	_DeclName_1[83:91]:        DeclTrapType,
	_DeclLowerName_1[83:91]:   DeclTrapType,
	_DeclName_1[91:102]:       DeclObjectGroup,
	_DeclLowerName_1[91:102]:  DeclObjectGroup,
	_DeclName_1[102:119]:      DeclNotificationGroup,
	_DeclLowerName_1[102:119]: DeclNotificationGroup,
	_DeclName_1[119:135]:      DeclModuleCompliance,
	_DeclLowerName_1[119:135]: DeclModuleCompliance,
	_DeclName_1[135:152]:      DeclAgentCapabilities,
	_DeclLowerName_1[135:152]: DeclAgentCapabilities,
	_DeclName_1[152:169]:      DeclTextualConvention,
	_DeclLowerName_1[152:169]: DeclTextualConvention,
	_DeclName_1[169:174]:      DeclMacro,
	_DeclLowerName_1[169:174]: DeclMacro,
	_DeclName_1[174:184]:      DeclComplGroup,
	_DeclLowerName_1[174:184]: DeclComplGroup,
	_DeclName_1[184:195]:      DeclComplObject,
	_DeclLowerName_1[184:195]: DeclComplObject,
	_DeclName_1[195:205]:      DeclImplObject,
	_DeclLowerName_1[195:205]: DeclImplObject,
	_DeclName_2[0:6]:          DeclModule,
	_DeclLowerName_2[0:6]:     DeclModule,
	_DeclName_2[6:15]:         DeclExtension,
	_DeclLowerName_2[6:15]:    DeclExtension,
	_DeclName_2[15:22]:        DeclTypedef,
	_DeclLowerName_2[15:22]:   DeclTypedef,
	_DeclName_2[22:26]:        DeclNode,
	_DeclLowerName_2[22:26]:   DeclNode,
	_DeclName_2[26:32]:        DeclScalar,
	_DeclLowerName_2[26:32]:   DeclScalar,
	_DeclName_2[32:37]:        DeclTable,
	_DeclLowerName_2[32:37]:   DeclTable,
	_DeclName_2[37:40]:        DeclRow,
	_DeclLowerName_2[37:40]:   DeclRow,
	_DeclName_2[40:46]:        DeclColumn,
	_DeclLowerName_2[40:46]:   DeclColumn,
	_DeclName_2[46:58]:        DeclNotification,
	_DeclLowerName_2[46:58]:   DeclNotification,
	_DeclName_2[58:63]:        DeclGroup,
	_DeclLowerName_2[58:63]:   DeclGroup,
	_DeclName_2[63:73]:        DeclCompliance,
	_DeclLowerName_2[63:73]:   DeclCompliance,
	_DeclName_2[73:81]:        DeclIdentity,
	_DeclLowerName_2[73:81]:   DeclIdentity,
	_DeclName_2[81:86]:        DeclClass,
	_DeclLowerName_2[81:86]:   DeclClass,
	_DeclName_2[86:95]:        DeclAttribute,
	_DeclLowerName_2[86:95]:   DeclAttribute,
	_DeclName_2[95:100]:       DeclEvent,
	_DeclLowerName_2[95:100]:  DeclEvent,
}

var _DeclNames = []string{
	_DeclName_0[0:7],
	_DeclName_0[7:19],
	_DeclName_0[19:33],
	_DeclName_1[0:14],
	_DeclName_1[14:29],
	_DeclName_1[29:39],
	_DeclName_1[39:53],
	_DeclName_1[53:67],
	_DeclName_1[67:83],
	_DeclName_1[83:91],
	_DeclName_1[91:102],
	_DeclName_1[102:119],
	_DeclName_1[119:135],
	_DeclName_1[135:152],
	_DeclName_1[152:169],
	_DeclName_1[169:174],
	_DeclName_1[174:184],
	_DeclName_1[184:195],
	_DeclName_1[195:205],
	_DeclName_2[0:6],
	_DeclName_2[6:15],
	_DeclName_2[15:22],
	_DeclName_2[22:26],
	_DeclName_2[26:32],
	_DeclName_2[32:37],
	_DeclName_2[37:40],
	_DeclName_2[40:46],
	_DeclName_2[46:58],
	_DeclName_2[58:63],
	_DeclName_2[63:73],
	_DeclName_2[73:81],
	_DeclName_2[81:86],
	_DeclName_2[86:95],
	_DeclName_2[95:100],
}

// DeclString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DeclString(s string) (Decl, error) {
	if val, ok := _DeclNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DeclNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Decl values", s)
}

// DeclValues returns all values of the enum
func DeclValues() []Decl {
	return _DeclValues
}

// DeclStrings returns a slice of all String values of the enum
func DeclStrings() []string {
	strs := make([]string, len(_DeclNames))
	copy(strs, _DeclNames)
	return strs
}

// IsADecl returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Decl) IsADecl() bool {
	for _, v := range _DeclValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Decl
func (i Decl) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Decl
func (i *Decl) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Decl should be a string, got %s", data)
	}

	var err error
	*i, err = DeclString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for Decl
func (i Decl) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Decl
func (i *Decl) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = DeclString(s)
	return err
}
