// Code generated by "enumer -type=IndexKind -trimprefix=IndexKind -json -yaml -output=indexkind_string.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _IndexKindName = "IndexUnknownIndexIndexIndexAugmentIndexReorderIndexSparseIndexExpand"

var _IndexKindIndex = [...]uint8{0, 12, 22, 34, 46, 57, 68}

const _IndexKindLowerName = "indexunknownindexindexindexaugmentindexreorderindexsparseindexexpand"

func (i IndexKind) String() string {
	if i < 0 || i >= IndexKind(len(_IndexKindIndex)-1) {
		return fmt.Sprintf("IndexKind(%d)", i)
	}
	return _IndexKindName[_IndexKindIndex[i]:_IndexKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IndexKindNoOp() {
	var x [1]struct{}
	_ = x[IndexUnknown-(0)]
	_ = x[IndexIndex-(1)]
	_ = x[IndexAugment-(2)]
	_ = x[IndexReorder-(3)]
	_ = x[IndexSparse-(4)]
	_ = x[IndexExpand-(5)]
}

var _IndexKindValues = []IndexKind{IndexUnknown, IndexIndex, IndexAugment, IndexReorder, IndexSparse, IndexExpand}

var _IndexKindNameToValueMap = map[string]IndexKind{
	_IndexKindName[0:12]:       IndexUnknown,
	_IndexKindLowerName[0:12]:  IndexUnknown,
	_IndexKindName[12:22]:      IndexIndex,
	_IndexKindLowerName[12:22]: IndexIndex,
	_IndexKindName[22:34]:      IndexAugment,
	_IndexKindLowerName[22:34]: IndexAugment,
	_IndexKindName[34:46]:      IndexReorder,
	_IndexKindLowerName[34:46]: IndexReorder,
	_IndexKindName[46:57]:      IndexSparse,
	_IndexKindLowerName[46:57]: IndexSparse,
	_IndexKindName[57:68]:      IndexExpand,
	_IndexKindLowerName[57:68]: IndexExpand,
}

var _IndexKindNames = []string{
	_IndexKindName[0:12],
	_IndexKindName[12:22],
	_IndexKindName[22:34],
	_IndexKindName[34:46],
	_IndexKindName[46:57],
	_IndexKindName[57:68],
}

// IndexKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IndexKindString(s string) (IndexKind, error) {
	if val, ok := _IndexKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IndexKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to IndexKind values", s)
}

// IndexKindValues returns all values of the enum
func IndexKindValues() []IndexKind {
	return _IndexKindValues
}

// IndexKindStrings returns a slice of all String values of the enum
func IndexKindStrings() []string {
	strs := make([]string, len(_IndexKindNames))
	copy(strs, _IndexKindNames)
	return strs
}

// IsAIndexKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i IndexKind) IsAIndexKind() bool {
	for _, v := range _IndexKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for IndexKind
func (i IndexKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for IndexKind
func (i *IndexKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("IndexKind should be a string, got %s", data)
	}

	var err error
	*i, err = IndexKindString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for IndexKind
func (i IndexKind) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for IndexKind
func (i *IndexKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = IndexKindString(s)
	return err
}
