// Code generated by "enumer -type=Language -trimprefix=Language -json -yaml -output=language_string.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _LanguageName = "UnknownSMIv1SMIv2SMIngSPPI"

var _LanguageIndex = [...]uint8{0, 7, 12, 17, 22, 26}

const _LanguageLowerName = "unknownsmiv1smiv2smingsppi"

func (i Language) String() string {
	if i < 0 || i >= Language(len(_LanguageIndex)-1) {
		return fmt.Sprintf("Language(%d)", i)
	}
	return _LanguageName[_LanguageIndex[i]:_LanguageIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LanguageNoOp() {
	var x [1]struct{}
	_ = x[LanguageUnknown-(0)]
	_ = x[LanguageSMIv1-(1)]
	_ = x[LanguageSMIv2-(2)]
	_ = x[LanguageSMIng-(3)]
	_ = x[LanguageSPPI-(4)]
}

var _LanguageValues = []Language{LanguageUnknown, LanguageSMIv1, LanguageSMIv2, LanguageSMIng, LanguageSPPI}

var _LanguageNameToValueMap = map[string]Language{
	_LanguageName[0:7]:        LanguageUnknown,
	_LanguageLowerName[0:7]:   LanguageUnknown,
	_LanguageName[7:12]:       LanguageSMIv1,
	_LanguageLowerName[7:12]:  LanguageSMIv1,
	_LanguageName[12:17]:      LanguageSMIv2,
	_LanguageLowerName[12:17]: LanguageSMIv2,
	_LanguageName[17:22]:      LanguageSMIng,
	_LanguageLowerName[17:22]: LanguageSMIng,
	_LanguageName[22:26]:      LanguageSPPI,
	_LanguageLowerName[22:26]: LanguageSPPI,
}

var _LanguageNames = []string{
	_LanguageName[0:7],
	_LanguageName[7:12],
	_LanguageName[12:17],
	_LanguageName[17:22],
	_LanguageName[22:26],
}

// LanguageString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LanguageString(s string) (Language, error) {
	if val, ok := _LanguageNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LanguageNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Language values", s)
}

// LanguageValues returns all values of the enum
func LanguageValues() []Language {
	return _LanguageValues
}

// LanguageStrings returns a slice of all String values of the enum
func LanguageStrings() []string {
	strs := make([]string, len(_LanguageNames))
	copy(strs, _LanguageNames)
	return strs
}

// IsALanguage returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Language) IsALanguage() bool {
	for _, v := range _LanguageValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Language
func (i Language) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Language
func (i *Language) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Language should be a string, got %s", data)
	}

	var err error
	*i, err = LanguageString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for Language
func (i Language) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Language
func (i *Language) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = LanguageString(s)
	return err
}
