// Code generated by "enumer -type=Render -trimprefix=Render -json -yaml -output=render_string.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_RenderName_0      = "NumericName"
	_RenderLowerName_0 = "numericname"
	_RenderName_1      = "Qualified"
	_RenderLowerName_1 = "qualified"
	_RenderName_2      = "Format"
	_RenderLowerName_2 = "format"
	_RenderName_3      = "Printable"
	_RenderLowerName_3 = "printable"
	_RenderName_4      = "Unknown"
	_RenderLowerName_4 = "unknown"
	_RenderName_5      = "All"
	_RenderLowerName_5 = "all"
)

var (
	_RenderIndex_0 = [...]uint8{0, 7, 11}
	_RenderIndex_1 = [...]uint8{0, 9}
	_RenderIndex_2 = [...]uint8{0, 6}
	_RenderIndex_3 = [...]uint8{0, 9}
	_RenderIndex_4 = [...]uint8{0, 7}
	_RenderIndex_5 = [...]uint8{0, 3}
)

func (i Render) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _RenderName_0[_RenderIndex_0[i]:_RenderIndex_0[i+1]]
	case i == 4:
		return _RenderName_1
	case i == 8:
		return _RenderName_2
	case i == 16:
		return _RenderName_3
	case i == 32:
		return _RenderName_4
	case i == 255:
		return _RenderName_5
	default:
		return fmt.Sprintf("Render(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RenderNoOp() {
	var x [1]struct{}
	_ = x[RenderNumeric-(1)]
	_ = x[RenderName-(2)]
	_ = x[RenderQualified-(4)]
	_ = x[RenderFormat-(8)]
	_ = x[RenderPrintable-(16)]
	_ = x[RenderUnknown-(32)]
	_ = x[RenderAll-(255)]
}

var _RenderValues = []Render{RenderNumeric, RenderName, RenderQualified, RenderFormat, RenderPrintable, RenderUnknown, RenderAll}

var _RenderNameToValueMap = map[string]Render{
	_RenderName_0[0:7]:       RenderNumeric,
	_RenderLowerName_0[0:7]:  RenderNumeric,
	_RenderName_0[7:11]:      RenderName,
	_RenderLowerName_0[7:11]: RenderName,
	_RenderName_1[0:9]:       RenderQualified,
	_RenderLowerName_1[0:9]:  RenderQualified,
	_RenderName_2[0:6]:       RenderFormat,
	_RenderLowerName_2[0:6]:  RenderFormat,
	_RenderName_3[0:9]:       RenderPrintable,
	_RenderLowerName_3[0:9]:  RenderPrintable,
	_RenderName_4[0:7]:       RenderUnknown,
	_RenderLowerName_4[0:7]:  RenderUnknown,
	_RenderName_5[0:3]:       RenderAll,
	_RenderLowerName_5[0:3]:  RenderAll,
}

var _RenderNames = []string{
	_RenderName_0[0:7],
	_RenderName_0[7:11],
	_RenderName_1[0:9],
	_RenderName_2[0:6],
	_RenderName_3[0:9],
	_RenderName_4[0:7],
	_RenderName_5[0:3],
}

// RenderString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RenderString(s string) (Render, error) {
	if val, ok := _RenderNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RenderNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Render values", s)
}

// RenderValues returns all values of the enum
func RenderValues() []Render {
	return _RenderValues
}

// RenderStrings returns a slice of all String values of the enum
func RenderStrings() []string {
	strs := make([]string, len(_RenderNames))
	copy(strs, _RenderNames)
	return strs
}

// IsARender returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Render) IsARender() bool {
	for _, v := range _RenderValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Render
func (i Render) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Render
func (i *Render) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Render should be a string, got %s", data)
	}

	var err error
	*i, err = RenderString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for Render
func (i Render) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Render
func (i *Render) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = RenderString(s)
	return err
}
