// Code generated by "enumer -type=Status -trimprefix=Status -json -yaml -output=status_string.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _StatusName = "UnknownCurrentDeprecatedMandatoryOptionalObsolete"

var _StatusIndex = [...]uint8{0, 7, 14, 24, 33, 41, 49}

const _StatusLowerName = "unknowncurrentdeprecatedmandatoryoptionalobsolete"

func (i Status) String() string {
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[StatusUnknown-(0)]
	_ = x[StatusCurrent-(1)]
	_ = x[StatusDeprecated-(2)]
	_ = x[StatusMandatory-(3)]
	_ = x[StatusOptional-(4)]
	_ = x[StatusObsolete-(5)]
}

var _StatusValues = []Status{StatusUnknown, StatusCurrent, StatusDeprecated, StatusMandatory, StatusOptional, StatusObsolete}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:7]:        StatusUnknown,
	_StatusLowerName[0:7]:   StatusUnknown,
	_StatusName[7:14]:       StatusCurrent,
	_StatusLowerName[7:14]:  StatusCurrent,
	_StatusName[14:24]:      StatusDeprecated,
	_StatusLowerName[14:24]: StatusDeprecated,
	_StatusName[24:33]:      StatusMandatory,
	_StatusLowerName[24:33]: StatusMandatory,
	_StatusName[33:41]:      StatusOptional,
	_StatusLowerName[33:41]: StatusOptional,
	_StatusName[41:49]:      StatusObsolete,
	_StatusLowerName[41:49]: StatusObsolete,
}

var _StatusNames = []string{
	_StatusName[0:7],
	_StatusName[7:14],
	_StatusName[14:24],
	_StatusName[24:33],
	_StatusName[33:41],
	_StatusName[41:49],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Status
func (i Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Status
func (i *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}

	var err error
	*i, err = StatusString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for Status
func (i Status) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Status
func (i *Status) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = StatusString(s)
	return err
}
