// Code generated by "enumer -type=FormatKind -trimprefix=FormatKind -json -yaml -output=format_string.go"; DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_FormatKindName_0      = "None"
	_FormatKindLowerName_0 = "none"
	_FormatKindName_1      = "EnumName"
	_FormatKindLowerName_1 = "enumname"
	_FormatKindName_2      = "EnumValue"
	_FormatKindLowerName_2 = "enumvalue"
	_FormatKindName_3      = "Bits"
	_FormatKindLowerName_3 = "bits"
	_FormatKindName_4      = "String"
	_FormatKindLowerName_4 = "string"
	_FormatKindName_5      = "Units"
	_FormatKindLowerName_5 = "units"
	_FormatKindName_6      = "DurationShort"
	_FormatKindLowerName_6 = "durationshort"
	_FormatKindName_7      = "All"
	_FormatKindLowerName_7 = "all"
)

var (
	_FormatKindIndex_0 = [...]uint8{0, 4}
	_FormatKindIndex_1 = [...]uint8{0, 8}
	_FormatKindIndex_2 = [...]uint8{0, 9}
	_FormatKindIndex_3 = [...]uint8{0, 4}
	_FormatKindIndex_4 = [...]uint8{0, 6}
	_FormatKindIndex_5 = [...]uint8{0, 5}
	_FormatKindIndex_6 = [...]uint8{0, 13}
	_FormatKindIndex_7 = [...]uint8{0, 3}
)

func (i FormatKind) String() string {
	switch {
	case i == 0:
		return _FormatKindName_0
	case i == 2:
		return _FormatKindName_1
	case i == 4:
		return _FormatKindName_2
	case i == 8:
		return _FormatKindName_3
	case i == 16:
		return _FormatKindName_4
	case i == 32:
		return _FormatKindName_5
	case i == 64:
		return _FormatKindName_6
	case i == 223:
		return _FormatKindName_7
	default:
		return fmt.Sprintf("FormatKind(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FormatKindNoOp() {
	var x [1]struct{}
	_ = x[FormatKindNone-(0)]
	_ = x[FormatKindEnumName-(2)]
	_ = x[FormatKindEnumValue-(4)]
	_ = x[FormatKindBits-(8)]
	_ = x[FormatKindString-(16)]
	_ = x[FormatKindUnits-(32)]
	_ = x[FormatKindDurationShort-(64)]
	_ = x[FormatKindAll-(223)]
}

var _FormatKindValues = []FormatKind{FormatKindNone, FormatKindEnumName, FormatKindEnumValue, FormatKindBits, FormatKindString, FormatKindUnits, FormatKindDurationShort, FormatKindAll}

var _FormatKindNameToValueMap = map[string]FormatKind{
	_FormatKindName_0[0:4]:       FormatKindNone,
	_FormatKindLowerName_0[0:4]:  FormatKindNone,
	_FormatKindName_1[0:8]:       FormatKindEnumName,
	_FormatKindLowerName_1[0:8]:  FormatKindEnumName,
	_FormatKindName_2[0:9]:       FormatKindEnumValue,
	_FormatKindLowerName_2[0:9]:  FormatKindEnumValue,
	_FormatKindName_3[0:4]:       FormatKindBits,
	_FormatKindLowerName_3[0:4]:  FormatKindBits,
	_FormatKindName_4[0:6]:       FormatKindString,
	_FormatKindLowerName_4[0:6]:  FormatKindString,
	_FormatKindName_5[0:5]:       FormatKindUnits,
	_FormatKindLowerName_5[0:5]:  FormatKindUnits,
	_FormatKindName_6[0:13]:      FormatKindDurationShort,
	_FormatKindLowerName_6[0:13]: FormatKindDurationShort,
	_FormatKindName_7[0:3]:       FormatKindAll,
	_FormatKindLowerName_7[0:3]:  FormatKindAll,
}

var _FormatKindNames = []string{
	_FormatKindName_0[0:4],
	_FormatKindName_1[0:8],
	_FormatKindName_2[0:9],
	_FormatKindName_3[0:4],
	_FormatKindName_4[0:6],
	_FormatKindName_5[0:5],
	_FormatKindName_6[0:13],
	_FormatKindName_7[0:3],
}

// FormatKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FormatKindString(s string) (FormatKind, error) {
	if val, ok := _FormatKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FormatKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FormatKind values", s)
}

// FormatKindValues returns all values of the enum
func FormatKindValues() []FormatKind {
	return _FormatKindValues
}

// FormatKindStrings returns a slice of all String values of the enum
func FormatKindStrings() []string {
	strs := make([]string, len(_FormatKindNames))
	copy(strs, _FormatKindNames)
	return strs
}

// IsAFormatKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FormatKind) IsAFormatKind() bool {
	for _, v := range _FormatKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FormatKind
func (i FormatKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FormatKind
func (i *FormatKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FormatKind should be a string, got %s", data)
	}

	var err error
	*i, err = FormatKindString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for FormatKind
func (i FormatKind) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for FormatKind
func (i *FormatKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = FormatKindString(s)
	return err
}
