// Code generated by "enumer -type=Format -trimprefix=Format -json -yaml -output=format_string.go"; DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_FormatName_0      = "None"
	_FormatLowerName_0 = "none"
	_FormatName_1      = "EnumName"
	_FormatLowerName_1 = "enumname"
	_FormatName_2      = "EnumValue"
	_FormatLowerName_2 = "enumvalue"
	_FormatName_3      = "Bits"
	_FormatLowerName_3 = "bits"
	_FormatName_4      = "String"
	_FormatLowerName_4 = "string"
	_FormatName_5      = "Units"
	_FormatLowerName_5 = "units"
	_FormatName_6      = "DurationShort"
	_FormatLowerName_6 = "durationshort"
	_FormatName_7      = "All"
	_FormatLowerName_7 = "all"
)

var (
	_FormatIndex_0 = [...]uint8{0, 4}
	_FormatIndex_1 = [...]uint8{0, 8}
	_FormatIndex_2 = [...]uint8{0, 9}
	_FormatIndex_3 = [...]uint8{0, 4}
	_FormatIndex_4 = [...]uint8{0, 6}
	_FormatIndex_5 = [...]uint8{0, 5}
	_FormatIndex_6 = [...]uint8{0, 13}
	_FormatIndex_7 = [...]uint8{0, 3}
)

func (i Format) String() string {
	switch {
	case i == 0:
		return _FormatName_0
	case i == 2:
		return _FormatName_1
	case i == 4:
		return _FormatName_2
	case i == 8:
		return _FormatName_3
	case i == 16:
		return _FormatName_4
	case i == 32:
		return _FormatName_5
	case i == 64:
		return _FormatName_6
	case i == 223:
		return _FormatName_7
	default:
		return fmt.Sprintf("Format(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FormatNoOp() {
	var x [1]struct{}
	_ = x[FormatNone-(0)]
	_ = x[FormatEnumName-(2)]
	_ = x[FormatEnumValue-(4)]
	_ = x[FormatBits-(8)]
	_ = x[FormatString-(16)]
	_ = x[FormatUnits-(32)]
	_ = x[FormatDurationShort-(64)]
	_ = x[FormatAll-(223)]
}

var _FormatValues = []Format{FormatNone, FormatEnumName, FormatEnumValue, FormatBits, FormatString, FormatUnits, FormatDurationShort, FormatAll}

var _FormatNameToValueMap = map[string]Format{
	_FormatName_0[0:4]:       FormatNone,
	_FormatLowerName_0[0:4]:  FormatNone,
	_FormatName_1[0:8]:       FormatEnumName,
	_FormatLowerName_1[0:8]:  FormatEnumName,
	_FormatName_2[0:9]:       FormatEnumValue,
	_FormatLowerName_2[0:9]:  FormatEnumValue,
	_FormatName_3[0:4]:       FormatBits,
	_FormatLowerName_3[0:4]:  FormatBits,
	_FormatName_4[0:6]:       FormatString,
	_FormatLowerName_4[0:6]:  FormatString,
	_FormatName_5[0:5]:       FormatUnits,
	_FormatLowerName_5[0:5]:  FormatUnits,
	_FormatName_6[0:13]:      FormatDurationShort,
	_FormatLowerName_6[0:13]: FormatDurationShort,
	_FormatName_7[0:3]:       FormatAll,
	_FormatLowerName_7[0:3]:  FormatAll,
}

var _FormatNames = []string{
	_FormatName_0[0:4],
	_FormatName_1[0:8],
	_FormatName_2[0:9],
	_FormatName_3[0:4],
	_FormatName_4[0:6],
	_FormatName_5[0:5],
	_FormatName_6[0:13],
	_FormatName_7[0:3],
}

// FormatString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FormatString(s string) (Format, error) {
	if val, ok := _FormatNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FormatNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Format values", s)
}

// FormatValues returns all values of the enum
func FormatValues() []Format {
	return _FormatValues
}

// FormatStrings returns a slice of all String values of the enum
func FormatStrings() []string {
	strs := make([]string, len(_FormatNames))
	copy(strs, _FormatNames)
	return strs
}

// IsAFormat returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Format) IsAFormat() bool {
	for _, v := range _FormatValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Format
func (i Format) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Format
func (i *Format) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Format should be a string, got %s", data)
	}

	var err error
	*i, err = FormatString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for Format
func (i Format) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Format
func (i *Format) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = FormatString(s)
	return err
}
